---
### RedHat Apache specific variables ###

apache_service: httpd
apache_daemon: httpd
apache_owner: apache
apache_daemon_path: /usr/sbin/
apache_server_root: /etc/httpd
apache_conf_path: /etc/httpd/conf.d
apache_modules_path: /etc/httpd/conf.modules.d

apache_packages:
  - httpd
  - httpd-devel
  - mod_ssl
  - openssh
