---
### Standard Default Variables ###
### The variables defined here are less likely needed to be modified

# Operating System Variables for database server
os_swappiness: 5
os_dirty_background_ratio: 5
os_dirty_ratio: 10
os_huge_page_size_KB: 2048

# Iris OS users and groups
os_irisgrp: irisgrp
os_irisusr: irisusr
os_irismgrgrp: irismgr
os_irismgrusr: irissys

# Credentials
smp_passwd: trakcare

# OS username for Iris backups
os_irisbackupusr: irisbackup

# Default variables that will be updated dynamically in runtime
iris_instance: iris
tc_nspace: "{{ tc_site|upper }}-{{ tc_env|upper }}"

# Define Iris instance name defaults
iris_instance_tc: "{{ tc_site|upper }}{{ tc_env|upper }}{{ tc_version }}TC"
iris_instance_int: "{{ tc_site|upper }}{{ tc_env|upper }}{{ tc_version }}INT"
iris_instance_prt: "{{ tc_site|upper }}{{ tc_env|upper }}{{ tc_version }}PRT"

# Iris instance target directory
iris_install_target_path: "{{ path_to_trak_iris }}"

# Iris journal directories
iris_jrnpri_path: "{{ path_to_trak_jrnpri }}"
iris_jrnalt_path: "{{ path_to_trak_jrnalt }}"
iris_wij_path: "{{ path_to_trak_wij }}"

# Database property variables
iris_db_expansionsizeMB: 1000
iris_globals8kb: 1024
iris_globals64kb: 64
iris_gmheap: 1048576
iris_locksiz: 268435456
iris_routines: 0,128,0,128,0,768
iris_DBSizesAllowed: 8192,65536
iris_type_server: LIVE

# RedHat Apache Iris conf file
apache_conf_filename: /etc/httpd/conf.d/ztrak.conf
apache_conf_nspace_filename: /etc/httpd/conf.d/ztrak_nspace.conf
apache_conf_template: template_tc_nspace_alias.conf


# Web Gateway
webgateway_opt_path: /opt/webgateway
cspgateway_csp_path: /usr/irissys
cspgateway_dbserver: "{{ iris_instance_tc }}"
webgateway_conf_file: /etc/httpd/conf.d/webgateway.conf
webgateway_conf_template: template_csp_ini.ini

# chmod permissions - leaving off the leading zero will likely have unexpected results.
tc_directory_mode: "0775"
tc_file_mode: "0664"
tc_database_mode: "0660"

# RedHat NFS service name
nfs_service: nfs

#FOP memory configuration
fop_memory: "512M"
