---
### Configure SELinux for Red Hat OS ###
### Filename:   /roles/web_server/tasks/configure-SELinux-wg.yml
### Author:     Carlos Sepulveda
### Now using ansible commands instead of OS-specific ones

- name: configure SELinux Web Gateway
  debug: msg="configure-SELinux-wg.yml"

# Configure SELinux to allow httpd read/write the following CSP Gateway files
- name: Allow apache to modify CSP.ini
  sefcontext:
    target: '{{ webgateway_opt_path }}/bin/CSP.ini'
    setype: httpd_sys_rw_content_t
    state: present
- name: Apply new SELinux file context to CSP.ini
  command: restorecon -irv {{ webgateway_opt_path }}/bin/CSP.ini

- name: Allow apache to modify CSPPRT.ini
  sefcontext:
    target: '{{ webgateway_opt_path }}/bin/CSPPRT.ini'
    setype: httpd_sys_rw_content_t
    state: present
- name: Apply new SELinux file context to CSP.ini
  command: restorecon -irv {{ webgateway_opt_path }}/bin/CSPPRT.ini

- name: Allow apache to modify CSP.log
  sefcontext:
    target: '{{ webgateway_opt_path }}/bin/CSP.log'
    setype: httpd_sys_rw_content_t
    state: present
- name: Apply new SELinux file context to CSP.ini
  command: restorecon -irv {{ webgateway_opt_path }}/bin/CSP.log

- name: Allow apache to modify Trak Web
  sefcontext:
    target: '{{ path_to_trak_web }}(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present
- name: Apply new SELinux file context to Trak Web
  command: restorecon -irv "{{ path_to_trak_web }}/"

# Configure the SELinux boolean allowing httpd to establish network connections
- name: allow Apache/Iris communication
  seport:
    ports: "{{ iris_superserver_port }}"
    proto: tcp
    setype: http_port_t
    state: present

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
