---
## Hack the Web Gateway
### Filename:   /roles/web_server/tasks/hack-webgateway.yml
### Author:    Carlos Sepulveda
### So many lines added, maybe good idea to replace with template...

# Restart Apache to initialise /opt/webgateway/bin/CSP.ini file
- name: restart Apache to initialise Web Gateway
  systemd:
    name: "{{ apache_service }}"
    state: restarted

# Horrible hack to me! I think this works...
- name: generate the passwd
  shell: echo -n "{{ smp_passwd }}" | base64
  register: csp_passwd

- name: template CSP.ini conf file out to web server
  template:
    src: "{{ webgateway_conf_template }}"
    dest: "{{ webgateway_opt_path }}/bin/CSP.ini"
